testing:
  pre_suct_time: 2.0
  suct_time: 0.5
  valve_us: 50000
  duty_regulator: 255

Params:
  duty_cycle: 100

optimization:
  dist_base: 0.5
  h_base: 0.4
  valve_0: 0.051
  g: 9.81
  IG_valve: 0.052
  IG_theta: 0.0
  bound_valve: [0.051, 0.5]
  bound_theta: [-90.0, 90.0]